<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Faker\Factory as Faker;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create('id_ID');
        $users = [
            [
                "name" => "admin",
                "username" => "admin123",
                "email" => "admin@gmail.com",
                "role" => "admin",
                "gender" => "L",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => "Jl. Raya Kampus Udayana",
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "BCA",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("admin123"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "customer123",
                "username" => "customer123",
                "email" => "customer123@gmail.com",
                "role" => "customer",
                "gender" => "L",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "BRI",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("customer123"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Farqy Noordien",
                "username" => "farqynoordien",
                "email" => "farqynoordien@gmail.com",
                "role" => "customer",
                "gender" => "L",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "BRI",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("farqynoordien"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Reynaldi Hamada",
                "username" => "reynaldihamada",
                "email" => "reynaldihamada@gmail.com",
                "role" => "customer",
                "gender" => "L",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "BRI",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("reynaldihamada"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Andrie Hidayat",
                "username" => "andriehidayat",
                "email" => "andriehidayat@gmail.com",
                "role" => "customer",
                "gender" => "L",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "BRI",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("andriehidayat"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Renita Syahidah",
                "username" => "renitasyahidah",
                "email" => "renitasyahidah@gmail.com",
                "role" => "customer",
                "gender" => "P",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "BNI",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("renitasyahidah"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Galuh Afini",
                "username" => "galuhafini",
                "email" => "galuhafini@gmail.com",
                "role" => "customer",
                "gender" => "P",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "BNI",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("galuhafini"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Desy Mustika",
                "username" => "desymustika",
                "email" => "desymustika@gmail.com",
                "role" => "customer",
                "gender" => "P",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "BNI",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("desymustika"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Lusiana Febrian",
                "username" => "lusianafebrian",
                "email" => "lusianafebrian@gmail.com",
                "role" => "customer",
                "gender" => "P",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "MANDIRI",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("lusianafebrian"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Anisah Widyatama",
                "username" => "anisahwidyatama",
                "email" => "anisahwidyatama@gmail.com",
                "role" => "customer",
                "gender" => "P",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "MANDIRI",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("anisahwidyatama"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Maharani Hutahaean",
                "username" => "maharanihutahaean",
                "email" => "maharanihutahaean@gmail.com",
                "role" => "customer",
                "gender" => "P",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "MANDIRI",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("maharanihutahaean"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Tari Octarina",
                "username" => "tarioctarina",
                "email" => "tarioctarina@gmail.com",
                "role" => "customer",
                "gender" => "P",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "BCA",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("tarioctarina"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Fika Shalimah",
                "username" => "fikashalimah",
                "email" => "fikashalimah@gmail.com",
                "role" => "customer",
                "gender" => "P",
                "province_id" => 35,
                "regency_id" => 3573,
                "district_id" => 3573050,
                "address" => $faker->address,
                "zip_code" => random_int(10000, 99999),
                "phone" => "08".random_int(100000000, 999999999),
                "bank_name" => "BCA",
                "bank_account" => random_int(100000, 999999),
                "password" => bcrypt("fikashalimah"),
                "verified" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ];
        User::insert($users);
    }
}
